/**
 * Shared interface primitives.
 *
 * `tone` threads a semantic colour through every component. It is not a styling
 * choice made per instance — cyan always means capacity, magenta always means
 * risk, amber always means cost, verdant always means value created, iris always
 * means output generated by Claude.
 */

import { motion } from 'framer-motion';
import type { ReactNode } from 'react';

export type Tone = 'photon' | 'plasma' | 'amber' | 'verdant' | 'iris' | 'neutral';

export const TONE_HEX: Record<Tone, string> = {
  photon: '#38e8ff',
  plasma: '#ff4fd8',
  amber: '#ffb547',
  verdant: '#4be39b',
  iris: '#8b7cff',
  neutral: '#8a93a6',
};

export const TONE_RGB: Record<Tone, string> = {
  photon: '56 232 255',
  plasma: '255 79 216',
  amber: '255 181 71',
  verdant: '75 227 155',
  iris: '139 124 255',
  neutral: '138 147 166',
};

/** Maps the sensitivity engine's tone names onto the interface's tone names. */
export function driverTone(tone: 'cyan' | 'magenta' | 'amber' | 'verdant' | 'iris'): Tone {
  if (tone === 'cyan') return 'photon';
  if (tone === 'magenta') return 'plasma';
  return tone;
}

// ---------------------------------------------------------------------------

export function GlassPanel({
  children,
  tone,
  className = '',
  as: _as,
}: {
  children: ReactNode;
  tone?: Exclude<Tone, 'neutral'>;
  className?: string;
  as?: never;
}) {
  return (
    <div className={`glass ${className}`} data-tone={tone}>
      <div className="relative z-10">{children}</div>
    </div>
  );
}

export function SectionShell({
  id,
  eyebrow,
  title,
  lede,
  children,
}: {
  id: string;
  eyebrow: string;
  title: string;
  lede?: string;
  children: ReactNode;
}) {
  return (
    // scroll-mt clears the fixed navigation bar when an anchor link jumps here.
    <section
      id={id}
      className="mx-auto w-full max-w-[1400px] scroll-mt-20 px-6 py-24 md:px-10"
    >
      <motion.header
        initial={{ opacity: 0, y: 24 }}
        whileInView={{ opacity: 1, y: 0 }}
        viewport={{ once: true, margin: '-80px' }}
        transition={{ duration: 0.6, ease: [0.22, 1, 0.36, 1] }}
        className="mb-10 max-w-3xl"
      >
        <p className="eyebrow mb-3">{eyebrow}</p>
        <h2 className="text-3xl md:text-4xl">{title}</h2>
        {lede && <p className="mt-4 text-slate-300 leading-relaxed">{lede}</p>}
      </motion.header>
      {children}
    </section>
  );
}

// ---------------------------------------------------------------------------

export type Verdict = 'pass' | 'fail' | 'watch' | 'none';

const VERDICT_TONE: Record<Verdict, Tone> = {
  pass: 'verdant',
  fail: 'plasma',
  watch: 'amber',
  none: 'neutral',
};

export function MetricTile({
  label,
  value,
  sub,
  hurdle,
  verdict = 'none',
  note,
  index = 0,
}: {
  label: string;
  value: string;
  sub?: string;
  hurdle?: string;
  verdict?: Verdict;
  note?: string;
  index?: number;
}) {
  const tone = VERDICT_TONE[verdict];

  /**
   * The verdict is carried by a top accent rail and an indicator dot, NOT by the
   * colour of the number. When most criteria fail, colouring every value by its
   * verdict floods the whole grid with one hue and the palette collapses to a
   * single accent. Keeping values near-white leaves the colour free to mean
   * something, and keeps the grid readable.
   */
  const longValue = value.length > 12;

  return (
    <motion.div
      initial={{ opacity: 0, y: 18 }}
      whileInView={{ opacity: 1, y: 0 }}
      viewport={{ once: true, margin: '-40px' }}
      transition={{ duration: 0.5, delay: index * 0.045, ease: [0.22, 1, 0.36, 1] }}
      className="glass relative overflow-hidden p-5"
    >
      {verdict !== 'none' && (
        <span
          className="absolute inset-x-0 top-0 h-px"
          style={{
            background: `linear-gradient(90deg, transparent, rgb(${TONE_RGB[tone]} / 0.85) 22%, rgb(${TONE_RGB[tone]} / 0.85) 78%, transparent)`,
          }}
        />
      )}
      <div className="relative z-10">
        <div className="flex items-start justify-between gap-3">
          <p className="text-[0.7rem] uppercase tracking-[0.14em] text-slate-400">{label}</p>
          {verdict !== 'none' && (
            <span
              className="mt-1 h-1.5 w-1.5 shrink-0 rounded-full"
              style={{
                background: TONE_HEX[tone],
                boxShadow: `0 0 8px rgb(${TONE_RGB[tone]} / 0.85)`,
              }}
            />
          )}
        </div>

        <p
          className={`numeric mt-3 leading-none text-slate-100 ${
            longValue ? 'text-xl md:text-[1.4rem]' : 'text-2xl md:text-[1.75rem]'
          }`}
        >
          {value}
        </p>

        {sub && <p className="numeric mt-2 text-xs text-slate-400">{sub}</p>}
        {hurdle && (
          <p className="mt-2 flex items-center gap-1.5 text-[0.7rem] text-slate-500">
            {verdict !== 'none' && (
              <span style={{ color: TONE_HEX[tone] }}>
                {verdict === 'pass' ? '✓' : verdict === 'fail' ? '✕' : '!'}
              </span>
            )}
            {hurdle}
          </p>
        )}
        {note && (
          <p className="mt-3 border-t border-white/5 pt-2 text-[0.7rem] leading-relaxed text-slate-400">
            {note}
          </p>
        )}
      </div>
    </motion.div>
  );
}

// ---------------------------------------------------------------------------

export function Field({
  label,
  hint,
  children,
  suffix,
}: {
  label: string;
  hint?: string;
  children: ReactNode;
  suffix?: string;
}) {
  return (
    <label className="block">
      <span className="mb-1.5 flex items-baseline justify-between gap-2">
        <span className="text-[0.78rem] text-slate-300">{label}</span>
        {suffix && <span className="numeric text-[0.68rem] text-slate-500">{suffix}</span>}
      </span>
      {children}
      {hint && <span className="mt-1.5 block text-[0.68rem] leading-snug text-slate-500">{hint}</span>}
    </label>
  );
}

export function SliderField({
  label,
  value,
  min,
  max,
  step,
  onChange,
  display,
  hint,
  tone = 'photon',
}: {
  label: string;
  value: number;
  min: number;
  max: number;
  step: number;
  onChange: (value: number) => void;
  display: string;
  hint?: string;
  tone?: Tone;
}) {
  return (
    <div>
      <div className="mb-2 flex items-baseline justify-between gap-2">
        <span className="text-[0.78rem] text-slate-300">{label}</span>
        <span className="numeric text-[0.82rem]" style={{ color: TONE_HEX[tone] }}>
          {display}
        </span>
      </div>
      <input
        type="range"
        min={min}
        max={max}
        step={step}
        value={value}
        onChange={(e) => onChange(Number(e.target.value))}
        style={{ ['--track-rgb' as string]: TONE_RGB[tone] }}
      />
      {hint && <p className="mt-1.5 text-[0.68rem] leading-snug text-slate-500">{hint}</p>}
    </div>
  );
}

// ---------------------------------------------------------------------------

export function Pill({
  children,
  tone = 'neutral',
}: {
  children: ReactNode;
  tone?: Tone;
}) {
  return (
    <span
      className="numeric inline-flex items-center gap-1.5 rounded-full px-2.5 py-1 text-[0.68rem]"
      style={{
        background: `rgb(${TONE_RGB[tone]} / 0.11)`,
        color: TONE_HEX[tone],
        border: `1px solid rgb(${TONE_RGB[tone]} / 0.25)`,
      }}
    >
      {children}
    </span>
  );
}

export function Callout({
  tone = 'iris',
  title,
  children,
}: {
  tone?: Tone;
  title: string;
  children: ReactNode;
}) {
  return (
    <div
      className="rounded-xl border p-4"
      style={{
        background: `rgb(${TONE_RGB[tone]} / 0.06)`,
        borderColor: `rgb(${TONE_RGB[tone]} / 0.22)`,
      }}
    >
      <p
        className="mb-1.5 text-[0.7rem] font-semibold uppercase tracking-[0.14em]"
        style={{ color: TONE_HEX[tone] }}
      >
        {title}
      </p>
      <div className="text-[0.82rem] leading-relaxed text-slate-300">{children}</div>
    </div>
  );
}
